"""adds foreign keys

Revision ID: 1f2912de883c
Revises: 64887c546ffa
Create Date: 2023-11-16 08:31:56.287653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2912de883c'
down_revision = '64887c546ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'item_id')
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
