"""add review

Revision ID: 64887c546ffa
Revises: 89e3dbfdb369
Create Date: 2023-11-16 08:19:03.531008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64887c546ffa'
down_revision = '89e3dbfdb369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
